//! # honest-tax-core
//!
//! A deterministic US federal income tax calculator.
//!
//! This crate provides the core calculation engine for computing federal income taxes.
//! It is designed to be:
//!
//! - **Deterministic**: Given the same inputs, always produces the same outputs
//! - **Accurate**: Uses exact decimal arithmetic to avoid floating-point errors
//! - **Extensible**: Supports multiple tax years through versioned rules
//! - **Type-safe**: Uses strong Rust types for all tax concepts
//!
//! ## Architecture
//!
//! The library is organized around three main concepts:
//!
//! - **Input forms**: Documents received by the taxpayer (W-2, 1099s, etc.)
//! - **Output forms**: Tax forms generated by the calculator (Form 1040, schedules)
//! - **Rules**: Year-specific tax parameters (brackets, deductions, credits)
//!
//! ## Example
//!
//! ```rust
//! use honest_tax_core::prelude::*;
//!
//! // Create a W-2
//! let w2 = W2 {
//!     id: "w2-001".to_string(),
//!     tax_year: 2025,
//!     employer_ein: "12-3456789".to_string(),
//!     employer_name: "Acme Corp".to_string(),
//!     employee_ssn: "123-45-6789".to_string(),
//!     employee_first_name: "John".to_string(),
//!     employee_last_name: "Doe".to_string(),
//!     box_1_wages: Money::from_dollars(75_000),
//!     box_2_federal_tax_withheld: Money::from_dollars(10_000),
//!     box_3_social_security_wages: Money::from_dollars(75_000),
//!     box_4_social_security_tax_withheld: Money::from_cents(465_000),
//!     box_5_medicare_wages: Money::from_dollars(75_000),
//!     box_6_medicare_tax_withheld: Money::from_cents(108_750),
//!     ..Default::default()
//! };
//!
//! // Load rules for 2025
//! let loader = RulesLoader::new();
//! let rules = loader.load(2025).unwrap();
//!
//! // Calculate tax
//! let tax = rules.calculate_tax(FilingStatus::Single, Money::from_dollars(50_000));
//! ```

pub mod error;
pub mod inputs;
pub mod money;
pub mod outputs;
pub mod rules;
pub mod traits;
pub mod types;

/// Prelude module for convenient imports.
pub mod prelude {
    pub use crate::error::{TaxError, TaxResult};
    pub use crate::inputs::W2;
    pub use crate::money::Money;
    pub use crate::outputs::Form1040;
    pub use crate::rules::RulesLoader;
    pub use crate::traits::{FormValue, InputForm, OutputForm, TaxRules};
    pub use crate::types::{
        Dependent, DependentRelationship, FilingStatus, InputFormType, OutputFormType, TaxYear,
        TaxpayerInfo,
    };
}

// Re-export commonly used items at crate root
pub use error::{TaxError, TaxResult};
pub use money::Money;
pub use types::FilingStatus;
